source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKLThreadSafeOperator_Example', :exclusive => true do
  pod "JKLThreadSafeOperator", :path => "../"
end

target 'JKLThreadSafeOperator_Tests', :exclusive => true do
  pod "JKLThreadSafeOperator", :path => "../"
#  pod 'Quick', '~> 0.8.0'
#  pod 'Nimble', '3.0.0'

  
end
